name: Generate Snake

# Controla quando o workflow vai correr
on:
  # Corre automaticamente a cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  
  # Permite correr manualmente
  workflow_dispatch:
  
  # Corre quando fazes push para a branch main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout do repositório
      - name: Checkout
        uses: actions/checkout@v3
      
      # Gera a animação da cobra
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: AndreTorga
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
      
      # Publica no GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
